# Find SNAPPY - A fast compressor/decompressor
#
# This module defines
#  SNAPPY_FOUND - whether the snappy library was found
#  SNAPPY_LIBRARIES - the snappy library
#  SNAPPY_INCLUDE_DIRS - the include path of the snappy library
#

if (SNAPPY_INCLUDE_DIR AND SNAPPY_LIBRARY)

  # Already in cache
  set (SNAPPY_FOUND TRUE)

else (SNAPPY_INCLUDE_DIR AND SNAPPY_LIBRARY)

IF (WIN32)
  FIND_PATH( SNAPPY_INCLUDE_DIR NAMES snappy.h 
    PATHS  
    $ENV{EXTERNLIBS}/snappy/include
    ${SNAPPY_ROOT_PATH}/include )
  FIND_LIBRARY( SNAPPY_LIBRARY_DEBUG NAMES snappyd
    PATHS
    $ENV{EXTERNLIBS}/snappy/lib
    ${SNAPPY_ROOT_PATH}/Debug
    )
    FIND_LIBRARY( SNAPPY_LIBRARY_RELEASE NAMES snappy
    PATHS
    $ENV{EXTERNLIBS}/snappy/lib
    ${SNAPPY_ROOT_PATH}/Release
    )
    IF(MSVC_IDE)
      IF (SNAPPY_LIBRARY_DEBUG AND SNAPPY_LIBRARY_RELEASE)
         SET(SNAPPY_LIBRARY optimized ${SNAPPY_LIBRARY_RELEASE} debug ${SNAPPY_LIBRARY_DEBUG})
      ELSE (SNAPPY_LIBRARY_DEBUG AND SNAPPY_LIBRARY_RELEASE)
         SET(SNAPPY_LIBRARY NOTFOUND)
         MESSAGE(STATUS "Could not find the debug AND release version of zlib")
      ENDIF (SNAPPY_LIBRARY_DEBUG AND SNAPPY_LIBRARY_RELEASE)
    ELSE(MSVC_IDE)
      STRING(TOLOWER ${CMAKE_BUILD_TYPE} CMAKE_BUILD_TYPE_TOLOWER)
      IF(CMAKE_BUILD_TYPE_TOLOWER MATCHES debug)
         SET(SNAPPY_LIBRARY ${SNAPPY_LIBRARY_DEBUG})
      ELSE(CMAKE_BUILD_TYPE_TOLOWER MATCHES debug)
         SET(SNAPPY_LIBRARY ${SNAPPY_LIBRARY_RELEASE})
      ENDIF(CMAKE_BUILD_TYPE_TOLOWER MATCHES debug)
    ENDIF(MSVC_IDE)
    MARK_AS_ADVANCED(SNAPPY_LIBRARY_DEBUG SNAPPY_LIBRARY_RELEASE)
  include(FindPackageHandleStandardArgs)
  find_package_handle_standard_args(SNAPPY DEFAULT_MSG SNAPPY_LIBRARY SNAPPY_LIBRARY_DEBUG SNAPPY_INCLUDE_DIR)
ELSE (WIN32)
  find_library (SNAPPY_LIBRARY
    NAMES
    snappy
    PATHS
  )

  find_path (SNAPPY_INCLUDE_DIR
    NAMES
    snappy.h
    PATHS
  )

  include(FindPackageHandleStandardArgs)
  find_package_handle_standard_args(SNAPPY DEFAULT_MSG SNAPPY_LIBRARY SNAPPY_INCLUDE_DIR)

ENDIF (WIN32)
endif (SNAPPY_INCLUDE_DIR AND SNAPPY_LIBRARY)

if (SNAPPY_FOUND)
   set (SNAPPY_INCLUDE_DIRS ${SNAPPY_INCLUDE_DIR})
   set (SNAPPY_LIBRARIES ${SNAPPY_LIBRARY})
endif()
