MACRO(USE_VTK)
  IF ((NOT VTK_FOUND) AND (${ARGC} LESS 1))
    MESSAGE("Skipping because of missing VTK")
    RETURN()
  ENDIF((NOT VTK_FOUND) AND (${ARGC} LESS 1))
  IF(NOT VTK_USED AND VTK_FOUND)
    SET(VTK_USED TRUE)
    IF(MSVC)
      SET(VTK_LIBRARIESIO debug vtkFilteringd optimized vtkFiltering debug vtkDICOMParserd optimized vtkDICOMParser debug vtkNetCDFd optimized vtkNetCDF debug vtkmetaiod optimized vtkmetaio debug vtksqlited optimized vtksqlite debug vtkpngd optimized vtkpng debug vtkzlibd optimized vtkzlib debug vtkjpegd optimized vtkjpeg debug vtktiffd optimized vtktiff debug vtkexpatd optimized vtkexpat debug vtksysd optimized vtksys general vfw32)
      SET(VTK_LIBRARIES debug vtkRenderingd optimized vtkRendering debug vtkGraphicsd optimized vtkGraphics debug vtkImagingd optimized vtkImaging debug vtkIOd optimized vtkIO debug vtkftgld optimized vtkftgl debug vtkfreetyped optimized vtkfreetype general opengl32)
      SET(VTK_LIBRARIESFILTERING debug vtkCommond optimized vtkCommon)
      SET(VTK_LIBRARIESCOMMON debug vtksysd optimized vtksys)
    
      LINK_DIRECTORIES(${VTK_LIBRARY_DIRS})
      INCLUDE_DIRECTORIES(${VTK_INCLUDE_DIRS})
      ADD_DEFINITIONS(-DHAVE_VTK)
      SET(EXTRA_LIBS ${EXTRA_LIBS} ${VTK_LIBRARIES} ${VTK_LIBRARIESIO} ${VTK_LIBRARIESFILTERING} ${VTK_LIBRARIESCOMMON})
    ELSE(MSVC)
      INCLUDE(${VTK_USE_FILE})
# atismer: works to find vtk-5.8 in opensuse 12.1
##testing
#      LINK_DIRECTORIES(${VTK_LIBRARY_DIRS})
#      INCLUDE(${VTK_CMAKE_DIR}/vtkMakeInstantiator.cmake)
##
      IF(MINGW)
          SET(EXTRA_LIBS ${EXTRA_LIBS} vtkCommon vtkGraphics vtkIO vtkFiltering)
      ELSE(MINGW)
          SET(EXTRA_LIBS ${EXTRA_LIBS} vtkCommon vtkGraphics vtkIO vtkRendering vtkFiltering)
      ENDIF(MINGW)
      ADD_DEFINITIONS(-DHAVE_VTK)
      IF(CMAKE_COMPILER_IS_GNUXX OR APPLE)
         SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-deprecated")
      ENDIF()
    ENDIF(MSVC)
  ENDIF()
ENDMACRO(USE_VTK)

