// EngineBuildingBlocks/Input/WindowsKeys.cpp

#include <EngineBuildingBlocks/Input/WindowsKeys.h>

#include <Core/Windows.h>

using namespace EngineBuildingBlocks::Input;

#define AddEntry(specificKey, generalKey)				\
	m_SpecificToGeneral[specificKey] = generalKey;		\
	m_GeneralToSpecific[(int)generalKey] = specificKey;

WindowsKeyMap::WindowsKeyMap()
{
	const int size = 512;
	m_GeneralToSpecific.PushBack(-1, static_cast<unsigned>(size));
	for (int i = 0; i < size; i++)
	{
		m_SpecificToGeneral[i] = EngineBuildingBlocks::Input::Keys::Unknown;
	}

	// Adding entries.
	AddEntry(VK_SPACE, EngineBuildingBlocks::Input::Keys::Space)
	AddEntry(VK_OEM_7, EngineBuildingBlocks::Input::Keys::Apostrophe)
	AddEntry(VK_OEM_COMMA, EngineBuildingBlocks::Input::Keys::Comma)
	AddEntry(VK_OEM_MINUS, EngineBuildingBlocks::Input::Keys::Minus)
	AddEntry(VK_OEM_PERIOD, EngineBuildingBlocks::Input::Keys::Period)
	AddEntry(VK_OEM_2, EngineBuildingBlocks::Input::Keys::Slash)
	AddEntry(VK_OEM_1, EngineBuildingBlocks::Input::Keys::Semicolon)
	AddEntry(VK_OEM_8, EngineBuildingBlocks::Input::Keys::Equal)
	AddEntry(VK_OEM_4, EngineBuildingBlocks::Input::Keys::LeftBracket)
	AddEntry(VK_OEM_5, EngineBuildingBlocks::Input::Keys::BackSlash)
	AddEntry(VK_OEM_6, EngineBuildingBlocks::Input::Keys::RightBracket)
	AddEntry(VK_OEM_3, EngineBuildingBlocks::Input::Keys::GraveAccent)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::World1)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::World2)
	AddEntry(0x30, EngineBuildingBlocks::Input::Keys::Key0)
	AddEntry(0x31, EngineBuildingBlocks::Input::Keys::Key1)
	AddEntry(0x32, EngineBuildingBlocks::Input::Keys::Key2)
	AddEntry(0x33, EngineBuildingBlocks::Input::Keys::Key3)
	AddEntry(0x34, EngineBuildingBlocks::Input::Keys::Key4)
	AddEntry(0x35, EngineBuildingBlocks::Input::Keys::Key5)
	AddEntry(0x36, EngineBuildingBlocks::Input::Keys::Key6)
	AddEntry(0x37, EngineBuildingBlocks::Input::Keys::Key7)
	AddEntry(0x38, EngineBuildingBlocks::Input::Keys::Key8)
	AddEntry(0x39, EngineBuildingBlocks::Input::Keys::Key9)
	AddEntry(0x41, EngineBuildingBlocks::Input::Keys::A)
	AddEntry(0x42, EngineBuildingBlocks::Input::Keys::B)
	AddEntry(0x43, EngineBuildingBlocks::Input::Keys::C)
	AddEntry(0x44, EngineBuildingBlocks::Input::Keys::D)
	AddEntry(0x45, EngineBuildingBlocks::Input::Keys::E)
	AddEntry(0x46, EngineBuildingBlocks::Input::Keys::F)
	AddEntry(0x47, EngineBuildingBlocks::Input::Keys::G)
	AddEntry(0x48, EngineBuildingBlocks::Input::Keys::H)
	AddEntry(0x49, EngineBuildingBlocks::Input::Keys::I)
	AddEntry(0x4A, EngineBuildingBlocks::Input::Keys::J)
	AddEntry(0x4B, EngineBuildingBlocks::Input::Keys::K)
	AddEntry(0x4C, EngineBuildingBlocks::Input::Keys::L)
	AddEntry(0x4D, EngineBuildingBlocks::Input::Keys::M)
	AddEntry(0x4E, EngineBuildingBlocks::Input::Keys::N)
	AddEntry(0x4F, EngineBuildingBlocks::Input::Keys::O)
	AddEntry(0x50, EngineBuildingBlocks::Input::Keys::P)
	AddEntry(0x51, EngineBuildingBlocks::Input::Keys::Q)
	AddEntry(0x52, EngineBuildingBlocks::Input::Keys::R)
	AddEntry(0x53, EngineBuildingBlocks::Input::Keys::S)
	AddEntry(0x54, EngineBuildingBlocks::Input::Keys::T)
	AddEntry(0x55, EngineBuildingBlocks::Input::Keys::U)
	AddEntry(0x56, EngineBuildingBlocks::Input::Keys::V)
	AddEntry(0x57, EngineBuildingBlocks::Input::Keys::W)
	AddEntry(0x58, EngineBuildingBlocks::Input::Keys::X)
	AddEntry(0x59, EngineBuildingBlocks::Input::Keys::Y)
	AddEntry(0x5A, EngineBuildingBlocks::Input::Keys::Z)
	AddEntry(VK_ESCAPE, EngineBuildingBlocks::Input::Keys::Escape)
	AddEntry(VK_RETURN, EngineBuildingBlocks::Input::Keys::Enter)
	AddEntry(VK_TAB, EngineBuildingBlocks::Input::Keys::Tab)
	AddEntry(VK_BACK, EngineBuildingBlocks::Input::Keys::Backspace)
	AddEntry(VK_INSERT, EngineBuildingBlocks::Input::Keys::Insert)
	AddEntry(VK_DELETE, EngineBuildingBlocks::Input::Keys::Delete)
	AddEntry(VK_RIGHT, EngineBuildingBlocks::Input::Keys::Right)
	AddEntry(VK_LEFT, EngineBuildingBlocks::Input::Keys::Left)
	AddEntry(VK_DOWN, EngineBuildingBlocks::Input::Keys::Down)
	AddEntry(VK_UP, EngineBuildingBlocks::Input::Keys::Up)
	AddEntry(VK_PRIOR, EngineBuildingBlocks::Input::Keys::PageUp)
	AddEntry(VK_NEXT, EngineBuildingBlocks::Input::Keys::PageDown)
	AddEntry(VK_HOME, EngineBuildingBlocks::Input::Keys::Home)
	AddEntry(VK_END, EngineBuildingBlocks::Input::Keys::End)
	AddEntry(VK_CAPITAL, EngineBuildingBlocks::Input::Keys::CapsLock)
	AddEntry(VK_SCROLL, EngineBuildingBlocks::Input::Keys::ScrollLock)
	AddEntry(VK_NUMLOCK, EngineBuildingBlocks::Input::Keys::NumLock)
	AddEntry(VK_PRINT, EngineBuildingBlocks::Input::Keys::PrintScreen)
	AddEntry(VK_PAUSE, EngineBuildingBlocks::Input::Keys::Pause)
	AddEntry(VK_F1, EngineBuildingBlocks::Input::Keys::F1)
	AddEntry(VK_F2, EngineBuildingBlocks::Input::Keys::F2)
	AddEntry(VK_F3, EngineBuildingBlocks::Input::Keys::F3)
	AddEntry(VK_F4, EngineBuildingBlocks::Input::Keys::F4)
	AddEntry(VK_F5, EngineBuildingBlocks::Input::Keys::F5)
	AddEntry(VK_F6, EngineBuildingBlocks::Input::Keys::F6)
	AddEntry(VK_F7, EngineBuildingBlocks::Input::Keys::F7)
	AddEntry(VK_F8, EngineBuildingBlocks::Input::Keys::F8)
	AddEntry(VK_F9, EngineBuildingBlocks::Input::Keys::F9)
	AddEntry(VK_F10, EngineBuildingBlocks::Input::Keys::F10)
	AddEntry(VK_F11, EngineBuildingBlocks::Input::Keys::F11)
	AddEntry(VK_F12, EngineBuildingBlocks::Input::Keys::F12)
	AddEntry(VK_NUMPAD0, EngineBuildingBlocks::Input::Keys::KeyPad0)
	AddEntry(VK_NUMPAD1, EngineBuildingBlocks::Input::Keys::KeyPad1)
	AddEntry(VK_NUMPAD2, EngineBuildingBlocks::Input::Keys::KeyPad2)
	AddEntry(VK_NUMPAD3, EngineBuildingBlocks::Input::Keys::KeyPad3)
	AddEntry(VK_NUMPAD4, EngineBuildingBlocks::Input::Keys::KeyPad4)
	AddEntry(VK_NUMPAD5, EngineBuildingBlocks::Input::Keys::KeyPad5)
	AddEntry(VK_NUMPAD6, EngineBuildingBlocks::Input::Keys::KeyPad6)
	AddEntry(VK_NUMPAD7, EngineBuildingBlocks::Input::Keys::KeyPad7)
	AddEntry(VK_NUMPAD8, EngineBuildingBlocks::Input::Keys::KeyPad8)
	AddEntry(VK_NUMPAD9, EngineBuildingBlocks::Input::Keys::KeyPad9)
	AddEntry(VK_DECIMAL, EngineBuildingBlocks::Input::Keys::KeyPadDecimal)
	AddEntry(VK_DIVIDE, EngineBuildingBlocks::Input::Keys::KeyPadDivide)
	AddEntry(VK_MULTIPLY, EngineBuildingBlocks::Input::Keys::KeyPadMultiply)
	AddEntry(VK_SUBTRACT, EngineBuildingBlocks::Input::Keys::KeyPadSubtract)
	AddEntry(VK_ADD, EngineBuildingBlocks::Input::Keys::KeyPadAdd)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::KeyPadEnter)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::KeyPadEqual)
	AddEntry(VK_LSHIFT, EngineBuildingBlocks::Input::Keys::LeftShift)
	AddEntry(VK_LCONTROL, EngineBuildingBlocks::Input::Keys::LeftControl)
	AddEntry(VK_LMENU, EngineBuildingBlocks::Input::Keys::LeftAlt)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::LeftSuper)
	AddEntry(VK_RSHIFT, EngineBuildingBlocks::Input::Keys::RightShift)
	AddEntry(VK_RCONTROL, EngineBuildingBlocks::Input::Keys::RightControl)
	AddEntry(VK_RMENU, EngineBuildingBlocks::Input::Keys::RightAlt)
	AddEntry(0, EngineBuildingBlocks::Input::Keys::RightSuper)
	AddEntry(VK_MENU, EngineBuildingBlocks::Input::Keys::Menu)
}