mklink /D config %COVISEDIR%\src\kernel\config
mklink /D file %COVISEDIR%\src\kernel\file
mklink /D fonts %COVISEDIR%\fonts
mklink /D gpu %COVISEDIR%\src\kernel\gpu
mklink /D grmsg %COVISEDIR%\src\kernel\grmsg
mklink /D icons %COVISEDIR%\icons
mklink /D net %COVISEDIR%\src\kernel\net
mklink /D OpenCOVER %COVISEDIR%\src\renderer\OpenCOVER
mklink /D sysdep %COVISEDIR%\src\kernel\sysdep
mklink /D tui %COVISEDIR%\src\kernel\tui
mklink /D util %COVISEDIR%\src\kernel\util
mklink /D virvo %COVISEDIR%\src\3rdparty\deskvox\virvo
mklink /D vrbclient %COVISEDIR%\src\kernel\vrbclient