["alias"]
# when Tubes is requested, start Thicken
Tubes = "Thicken"
TubesOld = "Thicken"
Spheres = "Thicken"
SpheresOld = "Thicken"
PrintAttributes = "PrintObjects"
CellSelect = "SelectCells"

["replace"]
# list of module groups that are able to replace each other
groups = [ "renderer", "select", "color", "clip", "attribute", "info" ]
# list all renderers - can replace each other
renderer = [ "COVER", "BlenderRenderer", "ANARemote", "DisCOVERay" ]
select = [ "Threshold", "CellSelect" ]
color = [ "Color", "ColorRandom" ]
clip = [ "CutGeometry", "ClipVtkm" ]
attribute = [ "AddAttribute", "AttachShader", "ColorAttribute", "EnableTransparency", "Variant" ]
info = [ "ObjectStatistics", "PrintAttributes", "PrintMetaData", "Extrema" ]
