use_openmp()

set(PREFER_TBB TRUE)
set(USE_TBB FALSE)

set(SOURCES ${SOURCES} ../IsoSurface/IsoSurface.cpp ../IsoSurface/IsoSurface.h ../IsoSurface/IsoDataFunctor.cpp ../IsoSurface/IsoDataFunctor.h)

if(FALSE AND VISTLE_USE_CUDA)
    set(USE_CUDA)
    add_definitions(-DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA)
    set(SOURCES ${SOURCES} "../IsoSurface/Leveller.cu")
else()
    set(SOURCES ${SOURCES} "../IsoSurface/Leveller.cpp")
    if(TBB_FOUND AND PREFER_TBB)
        add_definitions(-DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_TBB)
        set(USE_TBB TRUE)
    elseif(OPENMP_FOUND)
        add_definitions(-DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_OMP)
    elseif(TBB_FOUND)
        add_definitions(-DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_TBB)
        set(USE_TBB TRUE)
    else()
        add_definitions(-DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CPP)
    endif()
endif()

if(TBB_FOUND AND PREFER_TBB)
    add_definitions(-DUSE_TBB)
    add_definitions(-DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_TBB)
    set(USE_TBB TRUE)
elseif(OPENMP_FOUND)
    add_definitions(-DUSE_OMP)
    add_definitions(-DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_OMP)
    use_openmp()
elseif(TBB_FOUND)
    add_definitions(-DUSE_TBB)
    add_definitions(-DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_TBB)
    set(USE_TBB TRUE)
else()
    add_definitions(-DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP)
    add_definitions(-DUSE_CPP)
endif()

include_directories(SYSTEM ${THRUST_INCLUDE_DIR} ${TBB_INCLUDE_DIRS})

add_module(${NAME} ${DESCRIPTION} ${SOURCES})

if(USE_CUDA)
    target_include_directories(${NAME} PRIVATE SYSTEM ${CUDAToolkit_INCLUDE_DIRS})
endif()

if(USE_TBB)
    if(${CMAKE_GENERATOR} STREQUAL "Visual Studio 17 2022")
        target_link_libraries(${NAME} ${TBB_LIBRARIES})
    else()
        target_link_libraries(${NAME} TBB::tbb)
    endif()
endif()
