name: Make Release

on:
  push:
    tags:
      - v*
  release:
    types:
    - created
    - published
    - unpublished

jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Add version
        run: bin/_print_version.sh > .vistle_version.txt

      - name: Print cwd 1
        run: pwd >> "$GITHUB_OUTPUT"
      - name: Print cwd 2
        run: pwd
      - name: Ls 1
        run: ls -a
      - name: Ls 2
        run: ls -a >> "$GITHUB_OUTPUT"

      - name: Package source code including submodules
        uses: qmonnet/git-archive-all-action@v1
        with:
          output-files: vistle-${{ github.ref_name }}.tar.gz vistle-${{ github.ref_name }}.zip
          force-submodules: true
          extra-includes: .vistle-version.txt

      - name: Create draft release and add artifacts
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: vistle-*
