name: Make Release

on:
  push:
    tags:
      - v*
  release:
    types:
    - created
    - published
    - unpublished

jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          path: Vistle

      - name: Add version
        run: bin/_print_version.sh > .vistle_version.txt
        with:
          path: Vistle/vistle

      - name: Package source code including submodules
        uses: qmonnet/git-archive-all-action@v1
        with:
          path: Vistle
          output-files: vistle-${{ github.ref_name }}.tar.gz vistle-${{ github.ref_name }}.zip
          force-submodules: true
          extra-includes: .vistle-version.txt

      - name: Create draft release and add artifacts
        uses: softprops/action-gh-release@v1
        with:
          path: Vistle
          draft: true
          files: vistle-*
